### PR TITLE
Append query params when redirecting in language middleware

### LINKED ISSUE #3162: Responses table pagination not going to next "page"
## Description
Trying to paginate beyond the first 150 responses fails to paginate

## Steps to reproduce
1. Go to a form with over 150 responses. Responses 1-150 are shown.
2. Click on the "Next" link/button in the responses table
3. The original responses 1-150 are shown

## Expected behaviour
Clicking next shows the response 150-*

## Screenshots or videos
https://github.com/cds-snc/platform-forms-client/assets/107579368/ada8b214-1e2b-481d-a718-c74d0f771e8f

### PR DESCRIPTION
**Pull request by dsamojlenko**
# Summary | Résumé

Closes #3162 

Fixes pagination on Responses page by ensuring searchParams are appended to a URL when redirecting in the language middleware.

### CODE REVIEW

File: middleware.ts [hunk 1]
```diff
@@ -83,7 +84,8 @@ export async function middleware(req: NextRequest) {
       logMessage.debug(
         `Middleware - Redirecting to cookie language: ${cookieLang}, pathname: ${pathname}`
       );
-      return NextResponse.redirect(new URL(`/${cookieLang}${pathname}`, req.url));
+
+      return NextResponse.redirect(new URL(`/${cookieLang}${pathname}?${searchParams}`, req.url));
```
Comment (thiessenp-cds) [inline middleware.ts:88]: Minor nit pick to only include the question mark if any searchParams exist. Something like
```
`/${cookieLang}${pathname}${searchParams ?  "?"+searchParams : ""}`
```

**Review by thiessenp-cds — APPROVED** [review]
Tested, works great! Minor optional nit pick but LGTM :)
