### PR TITLE
Fix: Sort questions in Add Rule question list

### LINKED ISSUE #3702: Moving a question down doesn't change it's place in the list when adding a rule
**OS and Browser**
Mac
Chrome 

**Instructions to recreate**
1. Create a number element
2. Create a radio button for a conditional question
3. Copy the number element
4. Move the number element to the last position in the form
5. Add a rule to the radio button - notice that the dropdown doesn't change the position

In the picture above "unique client ID:" is actually the second last element in the form.

### PR DESCRIPTION
**Pull request by dsamojlenko**
# Summary | Résumé

- Includes a minor update to the sortByLayout function to operate on a copy of the elements array rather than the elements array itself.
- Adds a sortByGroups util function
- Fixes #3702

### CODE REVIEW

File: lib/utils/form-builder/index.ts [hunk 1]
```diff
@@ -92,11 +92,23 @@ export const sortByLayout = ({
...
 
+export const sortByGroups = ({
+  form,
+  elements,
+}: {
+  form: FormProperties;
+  elements: FormElement[];
+}) => {
+  const groups = form.groups || {};
+  const layout = getLayoutFromGroups(form, groups);
```
Comment (timarney) [inline lib/utils/form-builder/index.ts:108]: If groups is empty here can we skip the  getLayoutFromGroups call?

**Review by timarney — APPROVED** [review]
