### PR TITLE
fix: Update Regex for Nested Addresses to Match More Addressess

### LINKED ISSUE #4452: AddressComplete : Nested Address - Not displaying Full Amount of Addressess

### PR DESCRIPTION
**Pull request by ShadeWyrm**
Closes #4452

Issue was the RegEx was not returning correctly for certain addresses causing it to perform a normal search instead of a search by ID.

### CODE REVIEW

File: components/clientComponents/forms/AddressComplete/utils.ts [hunk 1]
```diff
@@ -150,7 +150,7 @@ export const getAddressAsAnswerElements = (
 
 // Helper function to test if the address has multiple results.
 export function matchesAddressPattern(input: string): boolean {
-  // See issue # 4417  
-  const pattern = /^.+,\s+[A-Z]{2}(?:,\s+[A-Z0-9]+)?\s+-\s+\d+\s+Addresses$/;
+  // Updated regex pattern to make the comma after the city name optional
```
Comment (timarney) [inline components/clientComponents/forms/AddressComplete/utils.ts:153]: We should keep a ref to the PR number and or try to explain in a comment what this regex is doing (what it's for --- when does this situation occur)

For the next dev I won't know what this is for and likely not even what a nested address is.

Comment (ShadeWyrm) [reply components/clientComponents/forms/AddressComplete/utils.ts:168]: Let me know if the comments I added sufficiently provide enough information. :)

**Review by timarney — APPROVED** [review]

File: components/clientComponents/forms/AddressComplete/utils.ts (hunk 1 above)
Comment (timarney) [reply components/clientComponents/forms/AddressComplete/utils.ts:168]: yup that works.
