### PR TITLE
fix: logout session end date

### LINKED ISSUE #945: Missing Session End Time - Log Out
The Log Out page is not displaying the Session End Time.

**Current implementation:**
- Leverages the session object on the page

**Fix Implementation**
- Use current date and time and set to browser time zone.  

**Reason:**
- Session object is not available because the session object has already been destroyed by the signOut function.

### PR DESCRIPTION
**Pull request by craigzour**
# Summary | Résumé

closes #945 

- Fixed session end date being displayed on logout page

Screen Shot 2022-08-25 at 11 48 37 AM

# Test instructions | Instructions pour tester la modification

- Run code contained in fix/logout-last-session-end-date branch
- Navigate to http://localhost:3000/auth/logout

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [x] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [x] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [x] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [x] Have you modified the change log and updated any relevant documentation?
- [x] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [x] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

File: pages/auth/logout.tsx [hunk 1]
```diff
@@ -1,22 +1,27 @@
...
 import { serverSideTranslations } from "next-i18next/serverSideTranslations";
 import { GetServerSideProps } from "next";
-import { useSession } from "next-auth/react";
 
 const Logout = () => {
   const { i18n, t } = useTranslation("logout");
-  const { data: session } = useSession();
+  const [lastLoginTime, setLastLoginTime] = useState("");
+
+  useEffect(() => {
```
Comment (craigzour) [inline pages/auth/logout.tsx:11]: `useEffect` was used to circumvent a [react-hydration-error](https://nextjs.org/docs/messages/react-hydration-error) because of the API being used to retrieve client's timezone.

File: pages/auth/logout.tsx [hunk 2]
```diff
@@ -1,22 +1,27 @@
...
 
   return (
     <>
       <div>
         <h2>{t("messageContent")}</h2>
         <div className="gc-last-login-time">
-          <>
-            {t("lastLoginTime")} : {session?.user?.lastLoginTime}
-          </>
+          {t("lastLoginTime")} : {lastLoginTime}
```
Comment (jeberhardt) [inline pages/auth/logout.tsx:24]: Why is this called "lastLoginTime"? Shouldn't it be "lastLogoutTime", since it is when the last session ended, not when it began.

File: pages/auth/logout.tsx [hunk 3]
```diff
@@ -1,22 +1,27 @@
...
-import { useSession } from "next-auth/react";
 
 const Logout = () => {
   const { i18n, t } = useTranslation("logout");
-  const { data: session } = useSession();
+  const [lastLoginTime, setLastLoginTime] = useState("");
+
+  useEffect(() => {
+    setLastLoginTime(
+      new Date().toLocaleString(`${i18n.language + "-CA"}`, {
```
Comment (jeberhardt) [inline pages/auth/logout.tsx:13]: Technically, it won't be the same date value as the last LOGOUT value in the `AccessLogs` table, but I suppose it'll be close enough that it won't matter.

**Review by falila — DISMISSED** [review]
Other than renaming the variable `lastLoginTime` name and the label key. It's all good.

File: pages/auth/logout.tsx (hunk 2 above)
Comment (craigzour) [reply pages/auth/logout.tsx:24]: You are right! Will change it

**Review by falila — APPROVED** [review]
🌮
