### PR TITLE
Fix last login time date format

### LINKED ISSUE #949: Last login time on acceptable use page was not formatted properly.
Not only the date/time wasn't formatted be understandable while using voiceOver but also the local (language) wasn't properly applied.

### PR DESCRIPTION
**Pull request by falila**
# Summary | Résumé
[Acceptable use page ](https://github.com/cds-snc/platform-forms-client/pull/911) PR must be merged before this PR. 
Once acceptable use PR merged this PR will be updated to only render changes related to time formatting. 
closed #949 
Before                                       
Screen Shot 2022-08-24 at 2 25 05 PM
After                                        
Screen Shot 2022-08-24 at 2 24 24 PM

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [ ] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [ ] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [x] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

File: components/auth/AcceptableUse.tsx [hunk 1]
```diff
@@ -59,7 +62,7 @@ export const AcceptableUseTerms = (props: AcceptableUseProps): React.ReactElemen
         <h1>{t("acceptableUsePage.welcome")}</h1>
         <span>
           <>
-            {t("acceptableUsePage.lastLoginTime")} : {lastLoginTime}
+            {t("acceptableUsePage.lastLoginTime")} : {time}
```
Comment (jeberhardt) [inline components/auth/AcceptableUse.tsx:65]: If `time` is undefined, should this <span> even be displayed?

Comment (jeberhardt) [reply components/auth/AcceptableUse.tsx:65]:
```
{ time && (
  <span>
    <>
      {t("acceptableUsePage.lastLoginTime")} : {time}
    </>
  </span>
  )}
  ```

Comment (falila) [reply components/auth/AcceptableUse.tsx:65]: You're right and i've thought about it but I'm not sure if that was the requirement. 
Either way showing  the label may quickly reveal that the feature is broken (visually).
